#!/bin/bash
echo "Deploying health check endpoint..."
echo ""
echo "To deploy, you need to run:"
echo "  supabase login"
echo "Then:"
echo "  supabase functions deploy health --project-ref lnagadkqejnopgfxwlkb --no-verify-jwt"
echo ""
echo "OR manually upload the function:"
echo "1. Go to: https://app.supabase.com/project/lnagadkqejnopgfxwlkb/functions"
echo "2. Click 'Create a new function'"
echo "3. Name it: health"
echo "4. Copy contents from: supabase/functions/health/index.ts"
echo "5. Deploy"
echo ""
echo "The function is ready at: supabase/functions/health/index.ts"
