// Standard error codes for categorization
export const ErrorCodes = {
  // Authentication/Authorization
  INVALID_SIGNATURE: 'INVALID_SIGNATURE',
  MISSING_AUTH_HEADER: 'MISSING_AUTH_HEADER',
  EXPIRED_TOKEN: 'EXPIRED_TOKEN',

  // Rate Limiting
  RATE_LIMITED: 'RATE_LIMITED',
  NONCE_REUSED: 'NONCE_REUSED',

  // Validation
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_COUNTRY_CODE: 'INVALID_COUNTRY_CODE',

  // Database
  DB_CONNECTION_ERROR: 'DB_CONNECTION_ERROR',
  DB_CONSTRAINT_VIOLATION: 'DB_CONSTRAINT_VIOLATION',
  DB_TIMEOUT: 'DB_TIMEOUT',

  // Business Logic
  CONTACT_NOT_FOUND: 'CONTACT_NOT_FOUND',
  DUPLICATE_TRANSACTION: 'DUPLICATE_TRANSACTION',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',

  // External Services
  EXTERNAL_API_ERROR: 'EXTERNAL_API_ERROR',
  EXTERNAL_API_TIMEOUT: 'EXTERNAL_API_TIMEOUT',

  // Unknown
  UNKNOWN_ERROR: 'UNKNOWN_ERROR'
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
