-- Find contact information using fuzzy matching
-- This query uses pg_trgm extension for fuzzy text matching

WITH search_names AS (
  SELECT unnest(ARRAY[
    'Virginia Jordan',
    'Laura Lea Lila Cannon',
    'All Seasons Chalice',
    'Tova Jacober',
    'Steiner King Foundation',
    'Harwood Ferguson',
    'Zettle Payments',
    'Margo King',
    'Furr Institute',
    'Derocher Family Charitable Fund',
    'Betsy Workman',
    'Barbara Simmons',
    'Candice Knight',
    'Corin Blanchard',
    'Brian Gray',
    'Susie Kincade',
    'Stefanie Smith',
    'Jim Paschis',
    'Sunshine Snow Removal LLC',
    'Stephanie Bollman',
    'Shana Stanberry Parker',
    'Olivia G Fischer',
    'Roberta Mylan',
    'Chien Lin',
    'CAYA Studios LLC',
    'Mary Thieme',
    'David Bork',
    'Colleen McCloskey',
    'Melissa Lago',
    'Iain Gillespie',
    'Robert B. Gass',
    'Anastacia Nutt',
    'Cristina Jeff Bowen',
    'Roy A. Wingate',
    'Christine Harvey',
    'William Melvin',
    'Three Swallows Foundation',
    'Tending the Sacred LLC',
    'Renee Goldberg',
    'Patricia Bowen',
    'Organic Roots Catering',
    'Mary Carpenter',
    'Marissa Bramlett',
    'Laine Gerritsen',
    'Jana Stratton',
    'Francesca Militeau',
    'Elaine Duncan',
    'David Weihnacht',
    'Cathleen Joshua Shoenfeld',
    'Abby Jepson-Kuhl',
    'Rebecca Arnold',
    'Jenna Buffaloe',
    'Amanda Pinelli Palumbo',
    'MJoy Silva',
    'Ryan Loo',
    'Michael Reisel',
    'Lisa Range',
    'Thomas Hast',
    'Mary Winston',
    'Marni Shymkus',
    'Marcia Kirsh Kohler',
    'Maggie Fox',
    'Lara Darvie',
    'Jessica W. Mazonson',
    'Jade MLynn',
    'Duncan Horst',
    'Deborah Ogden',
    'Brook Eddy',
    'Sydney Greene',
    'Katharine S. Roske',
    'Jack Swift',
    'Madhavii Shirman',
    'Steven Leovy',
    'Shannon OKane',
    'Daniel Rubenstein',
    'Morgan Botting',
    'Corey Strohmeyer',
    'Warren McCarty',
    'Scott Thurnauer',
    'Renee Del Gaudio',
    'Leah Stone',
    'Keith Whittier',
    'Kathleen Cameron Hallett',
    'Joyce LoDolce',
    'Jason Heartisan',
    'Gurpreet Gill',
    'Eric Fisher',
    'Debbie Burns',
    'Dayna Seraye LLC',
    'Laura Brown',
    'Daniela Papi Thornton',
    'Colorado Gives Foundation',
    'Elizabeth de Lorimier',
    'John Hazekamp',
    'Donna Renzetti',
    'Nicole Buckland',
    'Katie Brown',
    'Alexei Smirnov',
    'Christine Huston',
    'Beth McMacken',
    'Audrey Lecordier',
    'Amy Franz Garnsey',
    'Kimara Evans',
    'Shanti Medina',
    'Carey Albertine',
    'Sharona Hana',
    'Heather Baines',
    'The Star Trilogy',
    'Yetta Lee',
    'Wendy Nelson',
    'Thomas Bufano',
    'Tammie Helm',
    'Stephen Donnelly',
    'Stacey Benham',
    'Sherie Bruce',
    'Rita Haramy',
    'Richard Schooley',
    'Raki Suman',
    'Paula Slick',
    'Patricia Ramey',
    'Matthew Samek',
    'Mary Daye',
    'Mark Cronshaw',
    'Marjorie Kieselhorst-Eckart',
    'Mari Clements',
    'Marella. Colyvas',
    'Living Well Whole Health LLC',
    'Left Hand Laser Studio LLC',
    'Lauren Vilello',
    'Kirsten Hutcheson',
    'Kathryn Holt',
    'Kathryn Hampson',
    'John Meade',
    'Joan Soper',
    'Jen LeMarie',
    'Jason Rodgers',
    'Janeene Touchton',
    'Hsu Mei Chi',
    'Heather Ross',
    'Greg Temple',
    'Evelyn Eric Valen',
    'Emily Rose',
    'Elissa Langenegger',
    'Dyan Renee Hummel',
    'Diane Caracciolo',
    'Cindy Stark Reid',
    'Bradley Frey',
    'Barbara Hope-Gaiti',
    'Barbara Holden',
    'Angela Foster',
    'Amber Kinney',
    'Paul Humes',
    'Matthew Hainsworth',
    'Honeybee Herbals LLC',
    'Tara McConnell',
    'Amazon Smile',
    'Scott Burd',
    'Michelle Backus',
    'Martha Hopper',
    'Katherine Woller',
    'Brooke Rose LeVan',
    'Arisa La Fond',
    'Rahima B Dancy',
    'Mason Mostajo',
    'Torey Alford',
    'Stephen Clark',
    'Stefanie Briggs',
    'Peg Shippert',
    'Paulette Arnold',
    'Nicole Zelyez',
    'Makaysha Rain',
    'Liz DeGrave',
    'Lee Cook',
    'Kristin McLean',
    'Kristi Freeland',
    'Kimberly Cherry',
    'Kevin Natapow',
    'Kallie McGowan',
    'Julie Thomas',
    'Josiah Strauss',
    'Jeremy May',
    'Jennifer Miller',
    'Erika Vierke',
    'Eric Altman',
    'Dawn Deano',
    'Christina Cherry',
    'Carron Meaney',
    'Armene Piper',
    'Anonymous',
    'Alessandro Sacredoti',
    'Adam Swart'
  ]) AS search_name
),
contact_matches AS (
  SELECT DISTINCT ON (sn.search_name)
    sn.search_name,
    c.id,
    COALESCE(c.first_name || ' ' || c.last_name, c.paypal_business_name, c.email) AS matched_name,
    c.email,
    c.paypal_email AS email_2,
    c.phone,
    c.paypal_phone AS phone_2,
    GREATEST(
      similarity(LOWER(sn.search_name), LOWER(COALESCE(c.first_name || ' ' || c.last_name, ''))),
      similarity(LOWER(sn.search_name), LOWER(COALESCE(c.paypal_business_name, ''))),
      similarity(LOWER(sn.search_name), LOWER(COALESCE(c.paypal_first_name || ' ' || c.paypal_last_name, '')))
    ) AS match_score
  FROM search_names sn
  CROSS JOIN contacts c
  WHERE
    -- Use fuzzy matching with a threshold of 0.3 (lower = more lenient)
    (
      similarity(LOWER(sn.search_name), LOWER(COALESCE(c.first_name || ' ' || c.last_name, ''))) > 0.3
      OR similarity(LOWER(sn.search_name), LOWER(COALESCE(c.paypal_business_name, ''))) > 0.3
      OR similarity(LOWER(sn.search_name), LOWER(COALESCE(c.paypal_first_name || ' ' || c.paypal_last_name, ''))) > 0.3
    )
  ORDER BY sn.search_name, match_score DESC
),
additional_emails AS (
  SELECT
    cm.id AS contact_id,
    string_agg(DISTINCT ce.email, ', ' ORDER BY ce.email) AS additional_emails
  FROM contact_matches cm
  LEFT JOIN contact_emails ce ON ce.contact_id = cm.id
  WHERE ce.email IS NOT NULL
    AND ce.email != cm.email
    AND (cm.email_2 IS NULL OR ce.email != cm.email_2)
  GROUP BY cm.id
)
SELECT
  cm.search_name AS "Name",
  cm.matched_name AS "Matched Name",
  cm.match_score AS "Match Score",
  cm.email AS "Email",
  COALESCE(cm.email_2, ae.additional_emails) AS "Email 2",
  cm.phone AS "Phone",
  cm.phone_2 AS "Phone 2"
FROM contact_matches cm
LEFT JOIN additional_emails ae ON ae.contact_id = cm.id
ORDER BY cm.search_name;
